# SPDX-FileCopyrightText: 2025 Sebastian Andersson <sebastian@bittr.nu>
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "spoolman2klipper"
SPDX-PackageSupplier = "BlueBell-XA"
SPDX-PackageDownloadLocation = "https://github.com/BlueBell-XA/spoolman2klipper"

[[annotations]]
path = [
    ".github/**",
    ".gitignore",
    "**/__pycache__/**",
    "**/.pytest_cache/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 BlueBell-XA"
SPDX-License-Identifier = "CC0-1.0"
